apiVersion: apps/v1
kind: Deployment
metadata:
  name: namespace-configuration-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: namespace-configuration-operator
  template:
    metadata:
      labels:
        name: namespace-configuration-operator
    spec:
      serviceAccountName: namespace-configuration-operator
      containers:
        - name: namespace-configuration-operator
          # Replace this with the built image name
          image: quay.io/redhat-cop/namespace-configuration-operator:v0.2.0
          command:
          - namespace-configuration-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "namespace-configuration-operator"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace              
